wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.16.6
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715078917.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.10.2
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
data_path:
  desc: null
  value: data/Churn_Modelling.csv
batch_size:
  desc: null
  value: 128
num_epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0003
wandb_project:
  desc: null
  value: churnmod_priv_train
train_flag:
  desc: null
  value: 0
norm:
  desc: null
  value: 1
net_depth:
  desc: null
  value: 1
