wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707921406.438653
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
data_path:
  desc: null
  value: data/Churn_Modelling.csv
eps:
  desc: null
  value: 1.0
model_path:
  desc: null
  value: Models/churn_new_1
batch_size:
  desc: null
  value: 256
num_epochs:
  desc: null
  value: 300
learning_rate:
  desc: null
  value: 0.003
wandb_project:
  desc: null
  value: churn mod test
norm:
  desc: null
  value: 1
net_depth:
  desc: null
  value: 1
