wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.41.0.dev0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715087485.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.10.2
      5: 0.16.6
      6: 4.41.0.dev0
      8:
      - 1
      - 5
      13: linux-x86_64
