wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698992696.431994
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
data_path:
  desc: null
  value: data/covtype.csv
eps:
  desc: null
  value: 10.0
model_path:
  desc: null
  value: Models/net_1_cov
batch_size:
  desc: null
  value: 4096
num_epochs:
  desc: null
  value: 400
learning_rate:
  desc: null
  value: 0.003
wandb_project:
  desc: null
  value: covertype test
norm:
  desc: null
  value: 1
