wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.16.3
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712154605.136372
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 23
      4: 3.10.2
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
data_path:
  desc: null
  value: data/covtype.csv
eps:
  desc: null
  value: 1.0
model_path:
  desc: null
  value: Models/cov_full
batch_size:
  desc: null
  value: 4096
batch_size_priv:
  desc: null
  value: 4096
num_epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.0003
wandb_project:
  desc: null
  value: covertype test
norm:
  desc: null
  value: 1
net_depth:
  desc: null
  value: 1
device:
  desc: null
  value: cuda:2
